spring:
  application:
    name: game-session-service
  main:
    web-application-type: reactive

server:
  port: 8082

game-engine:
  url: ${GAME_ENGINE_URL:http://localhost:8081}

simulation:
  move-delay-ms: 400
